sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t eshmeister/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true eshmeister/react-test npm test

after_success:
  - docker build -t eshmeister/multi-docker-client ./client
  - docker build -t eshmeister/multi-docker-nginx ./nginx
  - docker build -t eshmeister/multi-docker-server ./server
  - docker build -t eshmeister/multi-docker-worker ./worker

  # Login to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  # Take the images and push to dockerhub
  - docker push eshmeister/multi-docker-client
  - docker push eshmeister/multi-docker-nginx
  - docker push eshmeister/multi-docker-server
  - docker push eshmeister/multi-docker-worker

deploy:
  edge: true
  provider: elasticbeanstalk
  region: us-east-1
  app: multi-docker-pern
  env: MultiDockerPern-env
  bucket_name: elasticbeanstalk-us-east-1-603236976063
  bucket_path: multi-docker-pern
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY

