sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t emushtaq/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true emushtaq/react-test npm test

after_success:
  - docker build -t emushtaq/multi-docker-client ./client
  - docker build -t emushtaq/multi-docker-nginx ./nginx
  - docker build -t emushtaq/multi-docker-server ./server
  - docker build -t emushtaq/multi-docker-worker ./worker

  # Login to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  # Take the images and push to dockerhub
  - docker push eshmeister/multi-docker-client
  - docker push eshmeister/multi-docker-nginx
  - docker push eshmeister/multi-docker-server
  - docker push eshmeister/multi-docker-worker

